const verbs = [{"id":1,"meaning":"SER/ESTAR","infinitive":"BE","past":"WAS/WERE","participle":"BEEN"},
{"id":2,"meaning":"LATIR","infinitive":"BEAT","past":"BEAT","participle":"BEATEN"},
{"id":3,"meaning":"CONVERTIRSE","infinitive":"BECOME","past":"BECAME","participle":"BECOME"},
{"id":4,"meaning":"COMENZAR","infinitive":"BEGIN","past":"BEGAN","participle":"BEGUN"},
{"id":5,"meaning":"DOBLAR","infinitive":"BEND","past":"BENT","participle":"BENT"},
{"id":6,"meaning":"APOSTAR","infinitive":"BET","past":"BET","participle":"BET"},
{"id":7,"meaning":"MORDER","infinitive":"BITE","past":"BIT","participle":"BITTEN"},
{"id":8,"meaning":"SANGRAR","infinitive":"BLEED","past":"BLED","participle":"BLED"},
{"id":9,"meaning":"SOPLAR","infinitive":"BLOW","past":"BLEW","participle":"BLOWN"},
{"id":10,"meaning":"ROMPER","infinitive":"BREAK","past":"BROKE","participle":"BROKEN"},
{"id":11,"meaning":"TRAER","infinitive":"BRING","past":"BROUGHT","participle":"BROUGHT"},
{"id":12,"meaning":"CONSTRUIR","infinitive":"BUILD","past":"BUILT","participle":"BUILT"},
{"id":13,"meaning":"QUEMAR","infinitive":"BURN","past":"BURNT","participle":"BURNT"},
{"id":14,"meaning":"COMPRAR","infinitive":"BUY","past":"BOUGHT","participle":"BOUGHT"},
{"id":15,"meaning":"COGER","infinitive":"CATCH","past":"CAUGHT","participle":"CAUGHT"},
{"id":16,"meaning":"ELEGIR","infinitive":"CHOOSE","past":"CHOSE","participle":"CHOSEN"},
{"id":17,"meaning":"VENIR","infinitive":"COME","past":"CAME","participle":"COME"},
{"id":18,"meaning":"COSTAR","infinitive":"COST","past":"COST","participle":"COST"},
{"id":19,"meaning":"CORTAR","infinitive":"CUT","past":"CUT","participle":"CUT"},
{"id":20,"meaning":"EXCAVAR","infinitive":"DIG","past":"DUG","participle":"DUG"},
{"id":21,"meaning":"HACER","infinitive":"DO","past":"DID","participle":"DONE"},
{"id":22,"meaning":"DIBUJAR","infinitive":"DRAW","past":"DREW","participle":"DRAWN"},
{"id":23,"meaning":"SOÑAR","infinitive":"DREAM","past":"DREAMT","participle":"DREAMT"},
{"id":24,"meaning":"BEBER","infinitive":"DRINK","past":"DRANK","participle":"DRUNK"},
{"id":25,"meaning":"CONDUCIR","infinitive":"DRIVE","past":"DROVE","participle":"DRIVEN"},
{"id":26,"meaning":"COMER","infinitive":"EAT","past":"ATE","participle":"EATEN"},
{"id":27,"meaning":"CAER","infinitive":"FALL","past":"FELL","participle":"FALLEN"},
{"id":28,"meaning":"ALIMENTAR","infinitive":"FEED","past":"FED","participle":"FED"},
{"id":29,"meaning":"SENTIR","infinitive":"FEEL","past":"FELT","participle":"FELT"},
{"id":30,"meaning":"LUCHAR","infinitive":"FIGHT","past":"FOUGHT","participle":"FOUGHT"},
{"id":31,"meaning":"ENCONTRAR","infinitive":"FIND","past":"FOUND","participle":"FOUND"},
{"id":32,"meaning":"VOLAR","infinitive":"FLY","past":"FLEW","participle":"FLOWN"},
{"id":33,"meaning":"OLVIDAR","infinitive":"FORGET","past":"FORGOT","participle":"FORGOTTEN"},
{"id":34,"meaning":"PERDONAR","infinitive":"FORGIVE","past":"FORGAVE","participle":"FORGIVEN"},
{"id":35,"meaning":"CONGELAR","infinitive":"FREEZE","past":"FROZE","participle":"FROZEN"},
{"id":36,"meaning":"OBTENER","infinitive":"GET","past":"GOT","participle":"GOT"},
{"id":37,"meaning":"DAR","infinitive":"GIVE","past":"GAVE","participle":"GIVEN"},
{"id":38,"meaning":"IR","infinitive":"GO","past":"WENT","participle":"GONE"},
{"id":39,"meaning":"CRECER","infinitive":"GROW","past":"GREW","participle":"GROWN"},
{"id":40,"meaning":"COLGAR","infinitive":"HANG","past":"HUNG","participle":"HUNG"},
{"id":41,"meaning":"TENER","infinitive":"HAVE","past":"HAD","participle":"HAD"},
{"id":42,"meaning":"OIR","infinitive":"HEAR","past":"HEARD","participle":"HEARD"},
{"id":43,"meaning":"ESCONDER","infinitive":"HIDE","past":"HID","participle":"HIDDEN"},
{"id":44,"meaning":"GOLPEAR","infinitive":"HIT","past":"HIT","participle":"HIT"},
{"id":45,"meaning":"SOSTENER","infinitive":"HOLD","past":"HELD","participle":"HELD"},
{"id":46,"meaning":"HERIR","infinitive":"HURT","past":"HURT","participle":"HURT"},
{"id":47,"meaning":"MANTENER","infinitive":"KEEP","past":"KEPT","participle":"KEPT"},
{"id":48,"meaning":"CONOCER","infinitive":"KNOW","past":"KNEW","participle":"KNOWN"},
{"id":49,"meaning":"YACER/TUMBARSE","infinitive":"LAY","past":"LAID","participle":"LAID"},
{"id":50,"meaning":"DIRIGIR","infinitive":"LEAD","past":"LED","participle":"LED"},
{"id":51,"meaning":"APRENDER","infinitive":"LEARN","past":"LEARNT","participle":"LEARNT"},
{"id":52,"meaning":"DEJAR","infinitive":"LEAVE","past":"LEFT","participle":"LEFT"},
{"id":53,"meaning":"PRESTAR","infinitive":"LEND","past":"LENT","participle":"LENT"},
{"id":54,"meaning":"PERMITIR","infinitive":"LET","past":"LET","participle":"LET"},
{"id":55,"meaning":"ALUMBRAR","infinitive":"LIGHT","past":"LIT","participle":"LIT"},
{"id":56,"meaning":"PERDER","infinitive":"LOSE","past":"LOST","participle":"LOST"},
{"id":57,"meaning":"HACER / CONSTRUIR","infinitive":"MAKE","past":"MADE","participle":"MADE"},
{"id":58,"meaning":"SIGNIFICAR","infinitive":"MEAN","past":"MEANT","participle":"MEANT"},
{"id":59,"meaning":"ENCONTRAR","infinitive":"MEET","past":"MET","participle":"MET"},
{"id":60,"meaning":"PAGAR","infinitive":"PAY","past":"PAID","participle":"PAID"},
{"id":61,"meaning":"PONER","infinitive":"PUT","past":"PUT","participle":"PUT"},
{"id":62,"meaning":"LEER","infinitive":"READ","past":"READ","participle":"READ"},
{"id":63,"meaning":"MONTAR / CABALGAR","infinitive":"RIDE","past":"RODE","participle":"RIDDEN"},
{"id":64,"meaning":"TOCAR / SONAR / LLAMAR","infinitive":"RING","past":"RANG","participle":"RUNG"},
{"id":65,"meaning":"SUBIR / AUMENTAR","infinitive":"RISE","past":"ROSE","participle":"RISEN"},
{"id":66,"meaning":"CORRER","infinitive":"RUN","past":"RAN","participle":"RUN"},
{"id":67,"meaning":"DECIR ALGO","infinitive":"SAY","past":"SAID","participle":"SAID"},
{"id":68,"meaning":"VER / MIRAR","infinitive":"SEE","past":"SAW","participle":"SEEN"},
{"id":69,"meaning":"VENDER","infinitive":"SELL","past":"SOLD","participle":"SOLD"},
{"id":70,"meaning":"ENVIAR","infinitive":"SEND","past":"SENT","participle":"SENT"},
{"id":71,"meaning":"COLOCAR / ESTABLECER","infinitive":"SET","past":"SET","participle":"SET"},
{"id":72,"meaning":"AGITAR","infinitive":"SHAKE","past":"SHOOK","participle":"SHAKEN"},
{"id":73,"meaning":"BRILLAR","infinitive":"SHINE","past":"SHONE","participle":"SHONE"},
{"id":74,"meaning":"CERRAR","infinitive":"SHUT","past":"SHUT","participle":"SHUT"},
{"id":75,"meaning":"DISPARAR","infinitive":"SHOOT","past":"SHOT","participle":"SHOT"},
{"id":76,"meaning":"MOSTRAR","infinitive":"SHOW","past":"SHOWED","participle":"SHOWN"},
{"id":77,"meaning":"CANTAR","infinitive":"SING","past":"SANG","participle":"SUNG"},
{"id":78,"meaning":"HUNDIR","infinitive":"SINK","past":"SANK","participle":"AUNK"},
{"id":79,"meaning":"SENTARSE","infinitive":"SIT","past":"SAT","participle":"SAT"},
{"id":80,"meaning":"DORMIR","infinitive":"SLEEP","past":"SLEPT","participle":"SLEPT"},
{"id":81,"meaning":"OLER","infinitive":"SMELL","past":"SMELT","participle":"SMELT"},
{"id":82,"meaning":"HABLAR","infinitive":"SPEAK","past":"SPOKE","participle":"SPOKEN"},
{"id":83,"meaning":"DELETREAR","infinitive":"SPELL","past":"SPELT","participle":"SPELT"},
{"id":84,"meaning":"GASTAR","infinitive":"SPEND","past":"SPENT","participle":"SPENT"},
{"id":85,"meaning":"ESTAR DE PIE","infinitive":"STAND","past":"STOOD","participle":"STOOD"},
{"id":86,"meaning":"ROBAR","infinitive":"STEAL","past":"STOLE","participle":"STOLEN"},
{"id":87,"meaning":"PEGAR","infinitive":"STICK","past":"STUCK","participle":"STUCK"},
{"id":88,"meaning":"NADAR","infinitive":"SWIM","past":"SWAM","participle":"SWUM"},
{"id":89,"meaning":"TOMAR","infinitive":"TAKE","past":"TOOK","participle":"TAKEN"},
{"id":90,"meaning":"ENSEÑAR","infinitive":"TEACH","past":"TOUGHT","participle":"TOUGHT"},
{"id":91,"meaning":"DESGARRAR","infinitive":"TEAR","past":"TORE","participle":"TORN"},
{"id":92,"meaning":"CONTAR","infinitive":"TELL","past":"TOLD","participle":"TOLD"},
{"id":93,"meaning":"PENSAR","infinitive":"THINK","past":"THOUGHT","participle":"THOUGHT"},
{"id":94,"meaning":"LANZAR","infinitive":"THROW","past":"THREW","participle":"THROWN"},
{"id":95,"meaning":"ENTENDER","infinitive":"UNDERSTAND","past":"UNDERSTOOD","participle":"UNDERSTOOD"},
{"id":96,"meaning":"DESPERTAR","infinitive":"WAKE","past":"WOKE","participle":"WOKEN"},
{"id":97,"meaning":"VESTIR / LLEVAR PUESTO","infinitive":"WEAR","past":"WORE","participle":"WORN"},
{"id":98,"meaning":"GANAR","infinitive":"WIN","past":"WON","participle":"WON"},
{"id":99,"meaning":"ESCRIBIR","infinitive":"WRITE","past":"WROTE","participle":"WRITTEN"}]